development: &default
  adapter: postgresql
  database: ledshop_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

production:
  <<: *default
  database: ledshop_db
  username: ledshop_user
  password: GWka3xe05G

staging:
  <<: *default
  database: ledshop_staging

test:
  <<: *default
  database: ledshop_test