---
- hosts: all
  name: System libs and Postgres Setup
  sudo: true
  roles:
    - common
    - role: ANXS.postgresql
      postgresql_ext_install_contrib: yes
      postgresql_users:
        - name: vagrant
          pass: vagrant
          encrypted: no
  tasks:
    - name: Grant Vagrant Superuser on Postgres
      postgresql_user:
        name: vagrant
        role_attr_flags: "SUPERUSER"

- hosts: all
  name: Ruby and Rails Setup
  sudo: true
  vars:
    rbenv_ruby_version: "2.2.0"
    rbenv_root: "/opt/rbenv"
  roles:
    - znzj.rbenv
    - app-config